export const cropsSeed = [
  { crop_id: "C001", crop_name: "Maize", scientific_name: "Zea mays", category: "Cereal", local_name_sw: "Mahindi", notes: "Staple cereal; widely grown across Kenya" },
  { crop_id: "C002", crop_name: "Common Bean", scientific_name: "Phaseolus vulgaris", category: "Legume", local_name_sw: "Maharagwe", notes: "Major intercrop with maize" },
  { crop_id: "C003", crop_name: "Tomato", scientific_name: "Solanum lycopersicum", category: "Vegetable", local_name_sw: "Nyanya", notes: "High-value horticultural crop" },
  { crop_id: "C004", crop_name: "Irish Potato", scientific_name: "Solanum tuberosum", category: "Tuber", local_name_sw: "Viazi", notes: "Major crop in highland counties e.g. Nyandarua, Meru" },
  { crop_id: "C005", crop_name: "Cassava", scientific_name: "Manihot esculenta", category: "Tuber", local_name_sw: "Muhogo", notes: "Drought-tolerant food security crop" },
  { crop_id: "C006", crop_name: "Banana", scientific_name: "Musa spp.", category: "Fruit", local_name_sw: "Ndizi", notes: "Grown widely in Central, Western, Coast regions" },
  { crop_id: "C007", crop_name: "Coffee", scientific_name: "Coffea arabica", category: "Cash crop", local_name_sw: "Kahawa", notes: "Major export cash crop, Central and Eastern Kenya" },
  { crop_id: "C008", crop_name: "Kale (Sukuma Wiki)", scientific_name: "Brassica oleracea var. acephala", category: "Vegetable", local_name_sw: "Sukuma Wiki", notes: "Most widely consumed leafy vegetable in Kenya" },
  { crop_id: "C009", crop_name: "Wheat", scientific_name: "Triticum aestivum", category: "Cereal", local_name_sw: "Ngano", notes: "Added from Janet Ndunda findings doc" },
  { crop_id: "C010", crop_name: "Mango", scientific_name: "Mangifera indica", category: "Fruit", local_name_sw: "Maembe", notes: "Added from Janet Ndunda findings doc" },
  { crop_id: "C011", crop_name: "Avocado", scientific_name: "Persea americana", category: "Fruit", local_name_sw: "Parachichi", notes: "Added from Janet Ndunda findings doc" },
  { crop_id: "C012", crop_name: "Groundnuts", scientific_name: "Arachis hypogaea", category: "Legume", local_name_sw: "Njugu", notes: "Added from Janet Ndunda findings doc" },
  { crop_id: "C013", crop_name: "Spinach", scientific_name: "Spinacia oleracea", category: "Vegetable", local_name_sw: "Mchicha (type)", notes: "Added from Janet Ndunda findings doc" },
  { crop_id: "C014", crop_name: "Lettuce", scientific_name: "Lactuca sativa", category: "Vegetable", local_name_sw: "Saladi", notes: "Added from Janet Ndunda findings doc" },
  { crop_id: "C015", crop_name: "Broccoli", scientific_name: "Brassica oleracea var. italica", category: "Vegetable", local_name_sw: "Brokoli", notes: "Added from Janet Ndunda findings doc" },
  { crop_id: "C016", crop_name: "Cabbage", scientific_name: "Brassica oleracea var. capitata", category: "Vegetable", local_name_sw: "Kabichi", notes: "Added from Janet Ndunda findings doc" },
  { crop_id: "C017", crop_name: "Various Seedlings", scientific_name: "", category: "Cross-crop (nursery stage)", local_name_sw: "Miche", notes: "Generic nursery/seedling stage, not crop-specific" }
];

export const officersSeed = [
  { officer_id: "AO001", full_name: "James Mwangi Karanja", organization: "Ministry of Agriculture - County Office", county: "Kiambu", specialization: "Crop Protection / Plant Pathology", phone_number: "+254 712 345 678", email: "j.karanja@kilimo.go.ke", years_experience: 12 },
  { officer_id: "AO002", full_name: "Grace Wanjiru Njoroge", organization: "KALRO (Kenya Agricultural & Livestock Research Org.)", county: "Nyandarua", specialization: "Potato & Horticulture", phone_number: "+254 722 456 789", email: "g.njoroge@kalro.org", years_experience: 8 },
  { officer_id: "AO003", full_name: "Daniel Otieno Owino", organization: "County Department of Agriculture", county: "Kisumu", specialization: "Rice & Cereal Crops", phone_number: "+254 733 567 890", email: "d.owino@kisumu.go.ke", years_experience: 15 },
  { officer_id: "AO004", full_name: "Fatuma Hassan Ali", organization: "Ministry of Agriculture - County Office", county: "Kilifi", specialization: "Cassava & Root Crops", phone_number: "+254 701 678 901", email: "f.ali@kilimo.go.ke", years_experience: 6 },
  { officer_id: "AO005", full_name: "Peter Kiprotich Langat", organization: "KALRO", county: "Uasin Gishu", specialization: "Maize & Cereal Pathology", phone_number: "+254 745 789 012", email: "p.langat@kalro.org", years_experience: 10 },
  { officer_id: "AO006", full_name: "Mary Achieng Odhiambo", organization: "County Department of Agriculture", county: "Bungoma", specialization: "Banana & Horticulture", phone_number: "+254 711 890 123", email: "m.odhiambo@bungoma.go.ke", years_experience: 9 },
  { officer_id: "AO007", full_name: "Samuel Kamau Ndungu", organization: "Coffee Research Institute (KALRO-CRI)", county: "Murang'a", specialization: "Coffee Pathology", phone_number: "+254 720 901 234", email: "s.ndungu@kalro.org", years_experience: 14 },
  { officer_id: "AO008", full_name: "Esther Chebet Korir", organization: "Ministry of Agriculture - County Office", county: "Nakuru", specialization: "Vegetables & Legumes", phone_number: "+254 798 012 345", email: "e.korir@kilimo.go.ke", years_experience: 7 }
];

export const usersSeed = [
  { user_id: "U001", full_name: "John Mwema Kamau", role: "Farmer", phone_number: "+254 712 111 222", county: "Kiambu", preferred_language: "Kiswahili", primary_crops_grown: "Maize, Beans", email: "john.kamau@farmmate.org", password: "Test@1234", date_registered: "2026-01-15", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200" },
  { user_id: "U002", full_name: "Susan Wairimu Mbugua", role: "Farmer", phone_number: "+254 722 222 333", county: "Nyandarua", preferred_language: "Kiswahili", primary_crops_grown: "Irish Potato, Kale", email: "susan.mbugua@farmmate.org", password: "Test@1234", date_registered: "2026-01-18", avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200" },
  { user_id: "U003", full_name: "Hassan Juma Mwakio", role: "Farmer", phone_number: "+254 733 333 444", county: "Kilifi", preferred_language: "Kiswahili", primary_crops_grown: "Cassava, Banana", email: "hassan.mwakio@farmmate.org", password: "Test@1234", date_registered: "2026-01-20", avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=200" },
  { user_id: "U004", full_name: "Lucy Nyambura Wanjiku", role: "Farmer", phone_number: "+254 701 444 555", county: "Murang'a", preferred_language: "English", primary_crops_grown: "Coffee, Beans", email: "lucy.wanjiku@farmmate.org", password: "Test@1234", date_registered: "2026-01-22", avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200" },
  { user_id: "U005", full_name: "Brian Otieno Ouma", role: "Farmer", phone_number: "+254 745 555 666", county: "Kisumu", preferred_language: "Kiswahili", primary_crops_grown: "Maize, Tomato", email: "brian.ouma@farmmate.org", password: "Test@1234", date_registered: "2026-01-25", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200" },
  { user_id: "U006", full_name: "Agnes Chepkemoi Ruto", role: "Farmer", phone_number: "+254 711 666 777", county: "Uasin Gishu", preferred_language: "English", primary_crops_grown: "Maize, Irish Potato", email: "agnes.ruto@farmmate.org", password: "Test@1234", date_registered: "2026-01-28", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200" },
  { user_id: "U007", full_name: "James Mwangi Karanja", role: "Agricultural Officer", phone_number: "+254 712 345 678", county: "Kiambu", preferred_language: "English", primary_crops_grown: "N/A", email: "james.karanja@kilimo.go.ke", password: "Test@1234", date_registered: "2026-01-10", avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200" },
  { user_id: "U008", full_name: "Grace Wanjiru Njoroge", role: "Agricultural Officer", phone_number: "+254 722 456 789", county: "Nyandarua", preferred_language: "English", primary_crops_grown: "N/A", email: "grace.njoroge@kalro.org", password: "Test@1234", date_registered: "2026-01-10", avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200" },
  { user_id: "U009", full_name: "Admin User", role: "Administrator", phone_number: "+254 700 000 001", county: "Nairobi", preferred_language: "English", primary_crops_grown: "N/A", email: "admin@farmmate.org", password: "Test@1234", date_registered: "2026-01-01", avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=200" },
  { user_id: "U010", full_name: "Test Tester Mwangi", role: "Farmer", phone_number: "+254 700 999 888", county: "Nakuru", preferred_language: "Kiswahili", primary_crops_grown: "Kale, Beans", email: "farmer@example.com", password: "Test@1234", date_registered: "2026-02-02", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200" }
];

export const historySeed = [
  { history_id: "H001", user_id: "U001", crop_id: "C001", disease_id: "D002", diagnosis_date: "2026-07-10", image: "https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&q=80&w=300", notes: "Detected during mid-season routine inspection." },
  { history_id: "H002", user_id: "U002", crop_id: "C004", disease_id: "D010", diagnosis_date: "2026-07-15", image: "https://images.unsplash.com/photo-1518977676601-b5ff321035b3?auto=format&fit=crop&q=80&w=300", notes: "Late Blight spreading fast due to high humidity levels." },
  { history_id: "H003", user_id: "U003", crop_id: "C003", disease_id: "D007", diagnosis_date: "2026-07-18", image: "https://images.unsplash.com/photo-1592841200221-a6898f307baa?auto=format&fit=crop&q=80&w=300", notes: "Late Blight spotted on southern leaves." },
  { history_id: "H004", user_id: "U004", crop_id: "C007", disease_id: "D020", diagnosis_date: "2026-07-19", image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=300", notes: "Coffee Leaf Rust detected. Heavy orange pustules underneath." },
  { history_id: "H005", user_id: "U010", crop_id: "C008", disease_id: "D022", diagnosis_date: "2026-07-20", image: "https://images.unsplash.com/photo-1606787366850-de6330128bfc?auto=format&fit=crop&q=80&w=300", notes: "Black Rot detected. Distinct yellow V-shapes." }
];
